/* generated by Svelte v3.23.2 */
import {
	SvelteComponent,
	append,
	attr,
	children,
	claim_element,
	claim_text,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	text
} from '/spa/web_modules/svelte/internal/index.js';

function create_fragment(ctx) {
	let footer;
	let div;
	let span;
	let t;

	return {
		c() {
			footer = element("footer");
			div = element("div");
			span = element("span");
			t = text("@Copyright 2020");
			this.h();
		},
		l(nodes) {
			footer = claim_element(nodes, "FOOTER", { class: true });
			var footer_nodes = children(footer);
			div = claim_element(footer_nodes, "DIV", { class: true });
			var div_nodes = children(div);
			span = claim_element(div_nodes, "SPAN", {});
			var span_nodes = children(span);
			t = claim_text(span_nodes, "@Copyright 2020");
			span_nodes.forEach(detach);
			div_nodes.forEach(detach);
			footer_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(div, "class", "text-white text-center font-semibold text-xl");
			attr(footer, "class", "bg-blue-500 h-10");
		},
		m(target, anchor) {
			insert(target, footer, anchor);
			append(footer, div);
			append(div, span);
			append(span, t);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(footer);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;